export const ExternalDirectoryTypeLabel = {
    OPEN_LDAP: 'USER_ADD_EXTERNAL_DIRECTORY_LDAP_SYNC_LABEL',
    ACTIVE_DIRECTORY: 'USER_ADD_EXTERNAL_DIRECTORY_AD_SYNC_LABEL',
    MICROSOFT_ENTRA_ID: 'USER_ADD_EXTERNAL_DIRECTORY_MS_ENTRA_ID_SYNC_LABEL'
}

